### ISSUE TITLE
initialise prevents using a different host than localhost

### ISSUE THREAD

**Issue by jasonmotylinski** [holidayextras/jsonapi-store-elasticsearch#5]
Hi - I'm trying to use the library against an Elasticsearch cluster hosted in AWS. I need to use a different hostname and it appears that initialise prevents me from setting the host value:

https://github.com/holidayextras/jsonapi-store-elasticsearch/blob/master/lib/elasticsearchHandler.js#L139

Is this the intent? If not, I can submit a pull request.

**Comment by theninj4** [comment]
Oh! You're correct, it's definitely not right. You're welcome to submit a PR for this :)
